elasticsearch:
  # Disable privileged init Container creation.
  sysctlInitContainer:
    enabled: false

  # Restrict the use of the memory-mapping when sysctlInitContainer is disabled.
  esConfig:
    elasticsearch.yml: |
      node.store.allow_mmap: false

  # Permit co-located instances for solitary virtual machines.
  antiAffinity: "soft"
  
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi

kibana:
  elasticsearchHosts: "http://elasticsearch-master:9200"
  ingress:
    enabled: true
    hosts: []
    tls:
      - secretName: kibana-ca
        hosts: []

fluent-bit:
  rbac:
    pspEnabled: true
  backend:
    type: es
    es:
      host: elasticsearch-master
      port: 9200
      # Elastic Index Name
      index: kubernetes_cluster
      type: flb_type
      logstash_prefix: kubernetes_cluster
      replace_dots: "On"
      logstash_format: "On"
      retry_limit: "False"
      time_key: "@timestamp"
       # Optional username credential for Elastic X-Pack access
      http_user:
      # Password for user defined in HTTP_User
      http_passwd:
      # Optional TLS encryption to ElasticSearch instance
      tls: "off"
      tls_verify: "on"
      # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
      tls_ca: ""
      # TLS debugging levels = 1-4
      tls_debug: 1