elasticsearch:
  # Disable privileged init Container creation.
  sysctlInitContainer:
    enabled: false

  # Restrict the use of the memory-mapping when sysctlInitContainer is disabled.
  esConfig:
    elasticsearch.yml: |
      node.store.allow_mmap: false

  # Permit co-located instances for solitary virtual machines.
  antiAffinity: "soft"
  
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi

kibana:
  elasticsearchHosts: "http://elasticsearch-master:9200"
  ingress:
    enabled: true
    hosts: []
    tls:
      - secretName: kibana-ca
        hosts: []

fluent-bit:
  image:
    repository: private-registry.prv.suse.net/dockerhub/fluent/fluent-bit
  podSecurityPolicy:
    create: true
  config:
    outputs: |
      [OUTPUT]
          Name es
          Match *
          Host elasticsearch-master
          Port 9200
          Logstash_Format On
          Retry_Limit False
          Type flb_type
          Replace_Dots On
          Logstash_Prefix kubernetes_cluster
