{{- if eq .Values.cluster_issuer "selfsigned" -}}
{{- $ca := genCA "ecosystemci-ca" 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: self-signed-ca
data:
  tls.crt: {{ $ca.Cert | b64enc | quote }}
  tls.key: {{ $ca.Key | b64enc | quote }}
{{- end -}}