{{- if .Values.cluster_issuer -}}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.cluster_issuer }}
  annotations:
    "helm.sh/hook": post-install
spec:
{{- if eq .Values.cluster_issuer "letsencrypt" }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ""
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
{{- else }}
  ca:
    secretName: self-signed-ca
  # selfSigned: {}
{{- end }}
{{- end -}}
