apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    "helm.sh/hook": post-install
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ""
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux