{{- $ca := genCA "kibana-ca" 365 }}
{{- $cert := genSignedCert (index .Values.kibana.ingress.hosts 0) nil (list (index .Values.kibana.ingress.hosts 0)) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "kibana-ca"
  labels:
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}